.TH lps 1 "2021-2022" "chkutil vol.2"
.SH NAME
lps \- useless system monitor (only cpu usage xd)

.SH SYNOPSIS
$
.B ./lps.c [
.B \-\-compile\-time%getpath
] [
.B \-\-compile\-time%cleanup
]

.SH DESCRIPTION
.B ./lps.c
compiles itself and runs. If executable already exists
it will be run without re-compilation. 

.SH OPTIONS
.TP
.B \-\-compile\-time%getpath
Displays current executable path and exit
.TP
.B \-\-compile\-time%cleanup
Cleans all executables and exit

.SH AUTHOR
.B lps
made by Amchik under
.B "chkutil vol.2"
project.

.SH SEE ALSO
top(1)
htop(1)

